[project]
name = "alex-v1"
requirements = [ ]
costs_version = 1

[contracts.alex-reserve-pool]
path = "contracts/pool/alex-reserve-pool.clar"
depends_on = [
  "trait-ownable",
  "trait-sip-010",
  "alex-vault",
  "age000-governance-token"
]

[contracts.futures-pool]
path = "contracts/pool/futures-pool.clar"
depends_on = [
  "trait-ownable",
  "trait-semi-fungible",
  "trait-multisig-vote",
  "alex-reserve-pool"
]

[contracts.staking-helper]
path = "contracts/helpers/staking-helper.clar"
depends_on = [ "alex-reserve-pool", "trait-sip-010" ]

[contracts.alex-vault]
path = "contracts/alex-vault.clar"
depends_on = [
  "trait-vault",
  "trait-sip-010",
  "trait-flash-loan-user",
  "trait-ownable",
  "trait-semi-fungible"
]

[contracts.collateral-rebalancing-pool]
path = "contracts/pool/collateral-rebalancing-pool.clar"
depends_on = [
  "trait-sip-010",
  "trait-vault",
  "alex-vault",
  "math-fixed-point",
  "weighted-equation",
  "fixed-weight-pool",
  "token-usda",
  "alex-reserve-pool",
  "yield-token-pool"
]

[contracts.yield-collateral-rebalancing-pool]
path = "contracts/pool/yield-collateral-rebalancing-pool.clar"
depends_on = [
  "trait-sip-010",
  "trait-vault",
  "math-fixed-point",
  "weighted-equation",
  "fixed-weight-pool",
  "token-usda",
  "alex-reserve-pool",
  "yield-token-pool"
]

[contracts.faucet]
path = "contracts/faucet.clar"
depends_on = [ "token-wbtc", "token-usda", "age000-governance-token", "token-wstx" ]

[contracts.fixed-weight-pool]
path = "contracts/pool/fixed-weight-pool.clar"
depends_on = [
  "alex-vault",
  "trait-sip-010",
  "trait-vault",
  "weighted-equation",
  "alex-reserve-pool",
  "trait-multisig-vote",
  "token-wstx"
]

[contracts.flash-loan-user-margin-usda-wbtc]
path = "contracts/flash-loan-user-margin-usda-wbtc.clar"
depends_on = [
  "trait-sip-010",
  "trait-flash-loan-user",
  "yield-wbtc",
  "key-wbtc-usda",
  "collateral-rebalancing-pool",
  "yield-token-pool",
  "fixed-weight-pool"
]

[contracts.flash-loan-user-margin-wstx-usda]
path = "contracts/flash-loan-user-margin-wstx-usda.clar"
depends_on = [
  "trait-sip-010",
  "trait-flash-loan-user",
  "token-wstx",
  "yield-usda",
  "key-usda-wstx",
  "collateral-rebalancing-pool",
  "yield-token-pool",
  "fixed-weight-pool"
]

[contracts.fwp-wstx-usda-50-50]
path = "contracts/pool-token/fwp-wstx-usda-50-50.clar"
depends_on = [ "trait-sip-010", "trait-ownable" ]

[contracts.fwp-wstx-wbtc-50-50]
path = "contracts/pool-token/fwp-wstx-wbtc-50-50.clar"
depends_on = [ "trait-sip-010", "trait-ownable" ]

[contracts.fwp-wstx-talex-50-50]
path = "contracts/pool-token/fwp-wstx-talex-50-50.clar"
depends_on = [ "trait-sip-010", "trait-ownable" ]

[contracts.key-usda-wbtc]
path = "contracts/key-token/key-usda-wbtc.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.key-usda-wstx]
path = "contracts/key-token/key-usda-wstx.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.liquidity-bootstrapping-pool]
path = "contracts/pool/liquidity-bootstrapping-pool.clar"
depends_on = [
  "trait-sip-010",
  "trait-vault",
  "math-fixed-point",
  "weighted-equation",
  "alex-reserve-pool",
  "token-usda",
  "fixed-weight-pool",
  "trait-multisig-vote",
  "alex-vault"
]

[contracts.margin-helper]
path = "contracts/helpers/margin-helper.clar"
depends_on = [
  "trait-sip-010",
  "trait-flash-loan-user",
  "collateral-rebalancing-pool",
  "fixed-weight-pool",
  "alex-vault"
]

[contracts.math-fixed-point]
path = "contracts/lib/math-fixed-point.clar"
depends_on = [ "math-log-exp" ]

[contracts.math-log-exp]
path = "contracts/lib/math-log-exp.clar"
depends_on = [ ]

[contracts.multisig-crp-usda-wstx]
path = "contracts/multisig/multisig-crp-usda-wstx.clar"
depends_on = [ "yield-usda", "key-usda-wstx", "collateral-rebalancing-pool" ]

[contracts.multisig-fwp-wstx-usda-50-50]
path = "contracts/multisig/multisig-fwp-wstx-usda-50-50.clar"
depends_on = [
  "fwp-wstx-usda-50-50",
  "math-fixed-point",
  "fixed-weight-pool"
]

[contracts.multisig-fwp-wstx-talex-50-50]
path = "contracts/multisig/multisig-fwp-wstx-talex-50-50.clar"
depends_on = [
  "fwp-wstx-talex-50-50",
  "math-fixed-point",
  "fixed-weight-pool"
]

[contracts.multisig-fwp-wstx-wbtc-50-50]
path = "contracts/multisig/multisig-fwp-wstx-wbtc-50-50.clar"
depends_on = [
  "fwp-wstx-wbtc-50-50",
  "math-fixed-point",
  "fixed-weight-pool"
]

[contracts.multisig-ytp-yield-wbtc]
path = "contracts/multisig/multisig-ytp-yield-wbtc.clar"
depends_on = [ "ytp-yield-wbtc", "yield-wbtc", "yield-token-pool" ]

[contracts.token-usda]
path = "contracts/token/token-usda.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-wbtc]
path = "contracts/token/token-wbtc.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-wstx]
path = "contracts/wrapped-token/token-wstx.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.trait-flash-loan-user]
path = "contracts/traits/trait-flash-loan-user.clar"
depends_on = [ "trait-sip-010" ]

[contracts.trait-multisig-vote]
path = "contracts/traits/trait-multisig-vote.clar"
depends_on = [ "trait-sip-010" ]

[contracts.trait-oracle]
path = "contracts/traits/trait-oracle.clar"
depends_on = [ ]

[contracts.trait-ownable]
path = "contracts/traits/trait-ownable.clar"
depends_on = [ ]

[contracts.trait-semi-fungible]
path = "contracts/traits/trait-semi-fungible.clar"
depends_on = [ ]

[contracts.trait-sip-010]
path = "contracts/traits/trait-sip-010.clar"
depends_on = [ ]

[contracts.trait-vault]
path = "contracts/traits/trait-vault.clar"
depends_on = [ "trait-sip-010", "trait-flash-loan-user" ]

[contracts.weighted-equation]
path = "contracts/equations/weighted-equation.clar"
depends_on = [ ]

[contracts.yield-token-equation]
path = "contracts/equations/yield-token-equation.clar"
depends_on = [ ]

[contracts.yield-token-pool]
path = "contracts/pool/yield-token-pool.clar"
depends_on = [
  "alex-vault",
  "trait-sip-010",
  "trait-vault",
  "trait-flash-loan-user",
  "math-fixed-point",
  "yield-token-equation",
  "trait-semi-fungible",
  "token-usda",
  "fixed-weight-pool",
  "alex-reserve-pool",
  "trait-multisig-vote"
]

[contracts.lbp-alex-usda-90-10]
path = "contracts/pool-token/lbp-alex-usda-90-10.clar"
depends_on = [ "trait-sip-010", "trait-ownable" ]

[contracts.multisig-lbp-alex-usda-90-10]
path = "contracts/multisig/multisig-lbp-alex-usda-90-10.clar"
depends_on = [ "lbp-alex-usda-90-10" ]

[contracts.multisig-crp-usda-wbtc]
path = "contracts/multisig/multisig-crp-usda-wbtc.clar"
depends_on = [
  "yield-usda",
  "key-usda-wbtc",
  "collateral-rebalancing-pool",
  "trait-semi-fungible",
  "trait-multisig-vote"
]

[contracts.multisig-crp-wbtc-wbtc]
path = "contracts/multisig/multisig-crp-wbtc-wbtc.clar"
depends_on = [
  "yield-wbtc",
  "key-wbtc-wbtc",
  "collateral-rebalancing-pool",
  "trait-semi-fungible",
  "trait-multisig-vote"
]

[contracts.multisig-crp-wbtc-usda]
path = "contracts/multisig/multisig-crp-wbtc-usda.clar"
depends_on = [
  "yield-wbtc",
  "key-wbtc-usda",
  "collateral-rebalancing-pool",
  "trait-multisig-vote"
]

[contracts.multisig-ytp-yield-usda]
path = "contracts/multisig/multisig-ytp-yield-usda.clar"
depends_on = [ "ytp-yield-usda", "yield-usda", "yield-token-pool" ]

[contracts.key-wbtc-usda]
path = "contracts/key-token/key-wbtc-usda.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.key-wbtc-wbtc]
path = "contracts/key-token/key-wbtc-wbtc.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.yield-usda]
path = "contracts/yield-token/yield-usda.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.yield-wbtc]
path = "contracts/yield-token/yield-wbtc.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.ytp-yield-usda]
path = "contracts/pool-token/ytp-yield-usda.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.ytp-yield-wbtc]
path = "contracts/pool-token/ytp-yield-wbtc.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.alex-launchpad]
path = "contracts/pool/alex-launchpad.clar"
depends_on = [ "trait-ownable", "trait-sip-010", "token-wstx" ]

[contracts.staked-alex]
path = "contracts/staked-token/staked-alex.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible" ]

[contracts.flash-loan-user-margin-wbtc-usda]
path = "contracts/flash-loan-user-margin-wbtc-usda.clar"
depends_on = [
  "trait-sip-010",
  "trait-flash-loan-user",
  "token-wbtc",
  "yield-usda",
  "key-usda-wbtc",
  "collateral-rebalancing-pool",
  "yield-token-pool",
  "fixed-weight-pool",
  "multisig-ytp-yield-wbtc",
  "multisig-ytp-yield-usda"
]

[contracts.lottery-t-alex]
path = "contracts/lottery-tokens/lottery-t-alex.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-unauthorised]
path = "contracts/tests/token-unauthorised.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.flash-loan-user-unauthorised]
path = "contracts/tests/flash-loan-user-unauthorised.clar"
depends_on = [ "trait-flash-loan-user" ]

[contracts.math-fixed-point-16]
path = "contracts/lib/math-fixed-point-16.clar"
depends_on = [ "math-log-exp-16" ]

[contracts.math-log-exp-16]
path = "contracts/lib/math-log-exp-16.clar"
depends_on = [ ]

[contracts.faucet-helper]
path = "contracts/helpers/faucet-helper.clar"
depends_on = [ "faucet" ]

[contracts.exchange]
path = "contracts/exchange.clar"
depends_on = [ "trait-ownable", "age000-governance-token" ]

[contracts.lottery-ido-alex]
path = "contracts/lottery-tokens/lottery-ido-alex.clar"
depends_on = ["trait-ownable", "trait-sip-010"]

[contracts.age000-governance-token]
path = "../executor-dao/contracts/extensions/age000-governance-token.clar"
depends_on = ["executor-dao", "governance-token-trait", "trait-sip-010"]

[contracts.age001-proposal-voting]
path = "../executor-dao/contracts/extensions/age001-proposal-voting.clar"
depends_on = ["executor-dao", "proposal-trait", "extension-trait", "governance-token-trait", "age000-governance-token"]

[contracts.age002-emergency-proposals]
path = "../executor-dao/contracts/extensions/age002-emergency-proposals.clar"
depends_on = ["executor-dao", "extension-trait", "age001-proposal-voting"]

[contracts.age003-emergency-execute]
path = "../executor-dao/contracts/extensions/age003-emergency-execute.clar"
depends_on = ["executor-dao", "extension-trait", "age001-proposal-voting"]

[contracts.agp000-bootstrap]
path = "../executor-dao/contracts/proposals/agp000-bootstrap.clar"

depends_on = ["executor-dao", "proposal-trait", "extension-trait", "age000-governance-token", "age001-proposal-voting", "age002-emergency-proposals", "age003-emergency-execute"]

[contracts.agp001-kill-emergency-execute]
path = "../executor-dao/contracts/proposals/agp001-kill-emergency-execute.clar"
depends_on = ["age003-emergency-execute", "executor-dao"]

[contracts.executor-dao]
path = "../executor-dao/contracts/executor-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]

[contracts.extension-trait]
path = "../executor-dao/contracts/traits/extension-trait.clar"
depends_on = []

[contracts.governance-token-trait]
path = "../executor-dao/contracts/traits/governance-token-trait.clar"
depends_on = []

[contracts.ownable-trait]
path = "../executor-dao/contracts/traits/ownable-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "../executor-dao/contracts/traits/proposal-trait.clar"
depends_on = []

[contracts.sip010-ft-trait]
path = "../executor-dao/contracts/traits/sip010-ft-trait.clar"
depends_on = []

[contracts.agp002-launchpad-alex]
path = "../executor-dao/contracts/proposals/agp002-launchpad-alex.clar"
depends_on = ["proposal-trait", "alex-launchpad", "lottery-ido-alex", "age000-governance-token"]
